[[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy = "default-src 'self' *.michelsen.dk https://*.disquscdn.com; connect-src 'self' *.disqus.com www.google-analytics.com *.googlesyndication.com https://*.googleapis.com; font-src 'self' data: https://*.gstatic.com; img-src 'self' *.apache.org *.cloudflare.com *.disqus.com *.disquscdn.com *.michelsen.dk data: https://*.googleapis.com *.googlesyndication.com https://*.gstatic.com https://*.staticflickr.com www.google-analytics.com; script-src 'self' 'unsafe-eval' 'unsafe-inline' *.cloudflare.com *.disqus.com https://*.disquscdn.com https://*.rawgit.com *.google.com *.googleapis.com *.gstatic.com *.googleadservices.com *.googletagservices.com *.googletagmanager.com www.google-analytics.com *.googlesyndication.com https://unpkg.com; style-src 'self' 'unsafe-inline' *.cloudflare.com *.disquscdn.com https://*.googleapis.com; frame-src disqus.com rawgit.com https://*.youtube.com *.doubleclick.net *.google.com *.googlesyndication.com; prefetch-src disqus.com *.disquscdn.com"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Frame-Options = "sameorigin"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[build]
  functions = "./functions"
